### ISSUE TITLE
pacman: download aborts due to false slowness

### ISSUE THREAD

**Issue by oscarfv** [msys2/MSYS2-packages#1660]
`pacman -Suy`, upgraded msys2/mintty, closed everything msys2-related, `pacman -Suy` again and...

```
:: Retrieving packages...
error: failed retrieving file 'mingw-w64-i686-llvm-8.0.0-3-any.pkg.tar.xz' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
```

but the download was proceeding at full speed (1.8 MB/s here). Pacman (or the tool it uses for downloading packages) does not notice that data is coming and aborts the download.

So it is impossible to upgrade any package that requires more than 10 seconds to download.

This is a very serious bug. People with slow connections will be forced to manually download and install msys2-runtime to fix this problem.

**Comment by Adsun701** [comment]
This has been fixed with #1659, which fixes msys2 curl to prevent this timeout error. The option --disable-download-timeout should mitigate pacman's timeout error before upgrading curl.

**Comment by oscarfv** [comment]
@Adsun701 : thanks for the quick response. Upgraded curl, libcurl, libidn2 and every other package outside the mingw-w64 namespace. The problem persists.

**Comment by oscarfv** [comment]
```
$ pacman -S libcurl curl
warning: libcurl-7.65.0-2 is up to date -- reinstalling
warning: curl-7.65.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (2) curl-7.65.0-2  libcurl-7.65.0-2
```

**Comment by angelog0** [comment]
I have the same issue. Today, after the upgrade of  `msys2-runtime* 3.0.7-3` packages, and the restart of `MinTTY`, `pacman` stopped working:

```

$ pacman -Syu
:: Sincronizzazione dei database in corso...
 mingw32                                   549,1 KiB   781K/s 00:01 [####################################] 100%
 mingw32.sig                               119,0   B  0,00B/s 00:00 [####################################] 100%
 mingw64 è aggiornato
 msys è aggiornato
:: Starting core system upgrade...
 non ci sono aggiornamenti disponibili
:: Aggiornamento del sistema in corso...
risoluzione delle dipendenze in corso...
ricerca dei pacchetti in conflitto in corso...

Pacchetti (12) mingw-w64-i686-gdb-8.3-3  mingw-w64-x86_64-clang-8.0.0-3
               mingw-w64-x86_64-clang-analyzer-8.0.0-3  mingw-w64-x86_64-clang-tools-extra-8.0.0-3
               mingw-w64-x86_64-compiler-rt-8.0.0-3  mingw-w64-x86_64-gdb-8.3-3
               mingw-w64-x86_64-harfbuzz-2.5.0-1  mingw-w64-x86_64-libc++-8.0.0-3
               mingw-w64-x86_64-libc++abi-8.0.0-3  mingw-w64-x86_64-lld-8.0.0-3  mingw-w64-x86_64-lldb-8.0.0-3
               mingw-w64-x86_64-llvm-8.0.0-3

Dimensione totale dei pacchetti da scaricare:    484,15 MiB
Dimensione totale dei pacchetti da installare:  2733,30 MiB
Dimensione netta dell'aggiornamento:              44,47 MiB

:: Vuoi procedere con l'installazione? [S/n]
:: Download dei pacchetti in corso...
 mingw-w64-i686-gdb-8.3-3-any                3,6 MiB  1132K/s 00:03 [####################################] 100%
errore: impossibile scaricare il pacchetto 'mingw-w64-x86_64-llvm-8.0.0-3-any.pkg.tar.xz' da repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
errore: impossibile scaricare il pacchetto 'mingw-w64-x86_64-llvm-8.0.0-3-any.pkg.tar.xz' da sourceforge.net : Operation timed out after 10014 milliseconds with 0 out of 0 bytes received
[...]
errore: impossibile eseguire l'operazione richiesta (errore inaspettato)
Si sono verificati degli errori, nessun pacchetto è stato aggiornato.

```

I tried many time but got only an `Abort..` and in the `HOME` it left `pacman.exe.stackdump`.

Any practical solution?

**Comment by oscarfv** [comment]
@angelog0 : see the comment from Adsun701 above about `--disable-download-timeout`.

**Comment by Mazwak** [comment]
I have the same problem.

I grabed pacman 5.1.2-2 from repo.msys2.org and installed it with pacman -U.

**Comment by oscarfv** [comment]
@Mazwak : the problematic packages are curl and libcurl. Either revert those or pass `--disable-download-timeout` to pacman.

**Comment by teepean** [comment]
I have experienced the same and now Pacman wants to replace ncurses with pdcurses.

`:: Starting full system upgrade...
:: Replace mingw-w64-i686-ncurses with mingw32/mingw-w64-i686-pdcurses? [Y/n] n
:: Replace mingw-w64-i686-termcap with mingw32/mingw-w64-i686-pdcurses? [Y/n] n
:: Replace mingw-w64-x86_64-ncurses with mingw64/mingw-w64-x86_64-pdcurses? [Y/n] n
:: Replace mingw-w64-x86_64-termcap with mingw64/mingw-w64-x86_64-pdcurses? [Y/n] n
resolving dependencies...
looking for conflicting packages...
:: mingw-w64-i686-pdcurses and mingw-w64-i686-ncurses are in conflict. Remove mingw-w64-i686-ncurses? [Y/n] y
:: mingw-w64-i686-pdcurses and mingw-w64-i686-termcap are in conflict. Remove mingw-w64-i686-termcap? [Y/n] y
:: mingw-w64-x86_64-pdcurses and mingw-w64-x86_64-ncurses are in conflict. Remove mingw-w64-x86_64-ncurses? [Y/n] n
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: mingw-w64-x86_64-pdcurses and mingw-w64-x86_64-ncurses are in conflict
`

**Comment by oscarfv** [comment]
@teepean : what you are observing is normal. The maintainer intentionally replaced `*-ncurses` and `*-termcap` with `*-pdcurses`. Just accept the change answering `y` to *all* the questions about the replacement.

**Comment by teepean** [comment]
> 
> 
> @teepean : what you are observing is normal. The maintainer intentionally replaced `*-ncurses` and `*-termcap` with `*-pdcurses`. Just accept the change answering `y` to _all_ the questions about the replacement.

Thanks! repo.msys2.org came back online and now pacman -Syu worked.

**Comment by ChinouneMehdi** [comment]
I have the same problem.
```bash
error: failed retrieving file 'mingw-w64-x86_64-binutils-2.30-6-any.pkg.tar.xz' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
```

**Comment by Adsun701** [comment]
It turns out pacman needed a rebuild against the fixed curl. The new pacman package just uploaded should work fine.

**Comment by oscarfv** [comment]
Yep, it works now. Thank you.
